# https://travis-ci.org/tornadoweb/tornado
language: python
python:
    - 2.7.8
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - nightly
    - pypy3
env:
    - TEST_SUITE=main
matrix:
    fast_finish: true

install: ./maint/travis/setup-$TEST_SUITE

script: ./maint/travis/$TEST_SUITE

after_success:
    # call codecov from project root
    - if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then cd ../ && codecov; fi

# This reportedly works around an issue downloading packages from pypi on
# travis.  Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false
