version: "3.7"
services:
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blog
    ports:
      - "3306"
  blog:
    build: .
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blog
    links:
      - postgres
    ports:
      - "8888:8888"
    entrypoint:
      - ./wait-for-postgres.sh
      - postgres
      - python3
      - blog.py
      - --db_host=postgres
